package com.matias.claudeusage;

/** Generado desde el diseño de las mascotas (16x16, pixel art). */
final class MascotData {
    static final String[] ANIMS = {"bob","squash","float","cat","robot","march","hover","chill","waddle"};
    static final Object[][] ALL = {
            {"Blob", 0, new String[][]{{"................",".....oooooo.....","...oobbbbbboo...","..obhhbbbbbbbo..","..obhbbbbbbbbo..",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","..obbbbbbbbbbo..","...oobbbbbboo...","....oo....oo....","................"}}, "b#D97757", new int[]{4,6,10,6}, new int[]{6,9}, new int[]{14,1}, "o", null, ""},
            {"Slime", 1, new String[][]{{"................",".......oo.......","......obbo......",".....ohhhbo.....","....ohhbbbbo....","...obhbbbbbbo...","..obhbbbbbbbbo..","..obbbbbbbbbbo..",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".odbbbbbbbbbbdo.","..oddddddddddo..","...oooooooooo...","................"}}, "b#4FA3E8", new int[]{5,8,9,8}, new int[]{6,11}, new int[]{13,3}, "o", null, ""},
            {"Fantasma", 2, new String[][]{{"................",".....oooooo.....","...oobbbbbboo...","..obhbbbbbbbbo..","..ohbbbbbbbbbo..",".obhbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbo.obbo.obbo.","..oo...oo...oo.."},{"................",".....oooooo.....","...oobbbbbboo...","..obhbbbbbbbbo..","..ohbbbbbbbbbo..",".obhbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbo.oo.obbbo.","..ooo......ooo.."}}, "b#E9E4FF,o#3B3366", new int[]{4,7,10,7}, new int[]{6,10}, new int[]{14,2}, "k", null, ""},
            {"Gato", 3, new String[][]{{"................","..o..........o..",".opo........opo.",".opbo......obpo.",".obbboooooobbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","oobbbbbbbbbbbboo",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","...oobbbbbboo...",".....oooooo.....","................","................","................"},{"................",".............o..","............opo.",".oooo......obpo.",".obbboooooobbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","oobbbbbbbbbbbboo",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","...oobbbbbboo...",".....oooooo.....","................","................","................"}}, "b#F2A65A", new int[]{4,6,10,6}, new int[]{6,9}, new int[]{14,4}, "o", new int[]{7,8}, ""},
            {"Robot", 4, new String[][]{{".......rr.......",".......oo.......",".......oo.......",".......oo.......","...oooooooooo...","..ohbbbbbbbbbo..","..ohkkkkkkkkbo..","..obkkkkkkkkbo..","..obkkkkkkkkbo..","..obbbbbbbbbbo..","..obbbbbbbbbbo..","..obbbbbbbbbbo..","..obbbbbbbbbbo..","...oooooooooo...","....obbbbbbo....","....oooooooo...."},{".......yy.......",".......oo.......",".......oo.......",".......oo.......","...oooooooooo...","..ohbbbbbbbbbo..","..ohkkkkkkkkbo..","..obkkkkkkkkbo..","..obkkkkkkkkbo..","..obbbbbbbbbbo..","..obbbbbbbbbbo..","..obbbbbbbbbbo..","..obbbbbbbbbbo..","...oooooooooo...","....obbbbbbo....","....oooooooo...."}}, "b#9AA7B8", new int[]{5,7,9,7}, new int[]{6,10}, new int[]{14,4}, "c", null, ""},
            {"Invasor", 5, new String[][]{{"................","................","................","................","..b..........b..","...b........b...","..bbbbbbbbbbbb..",".bb.bbbbbbbb.bb.","bbbbbbbbbbbbbbbb","b.bbbbbbbbbbbb.b","b.b..........b.b","...bb......bb...","................","................","................","................"},{"................","................","................","................","..b..........b..","...b........b...","b.bbbbbbbbbbbb.b","bbb.bbbbbbbb.bbb","bbbbbbbbbbbbbbbb","..bbbbbbbbbbbb..","................",".bb..........bb.","................","................","................","................"}}, "b#7CF57C", new int[]{3,7,12,7}, null, new int[]{14,3}, "k", null, "n"},
            {"Dragoncito", 6, new String[][]{{"................","...y........y...","..oyo......oyo..","..obboooooobbo..","..obbbbbbbbbbo..",".sbbbbbbbbbbbbs.","sobbbbbbbbbbbbos","sobbbbbbbbbbbbos",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","..obssssssssbo..","...osssssssso...","....oooooooo....","....o..oo..o....","................"},{"................","...y........y...","..oyo......oyo..","..obboooooobbo..","..obbbbbbbbbbo..",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","sobbbbbbbbbbbbos","s.obbbbbbbbbbo.s",".sobssssssssbos.","...osssssssso...","....oooooooo....","....o..oo..o....","................"}}, "b#59C28C,s#F6D186", new int[]{4,6,10,6}, new int[]{6,9}, new int[]{14,3}, "o", null, ""},
            {"Ninja", 0, new String[][]{{"................",".....oooooo.....","...ookkkkkkoo...","..okkkkkkkkkko..","..okkkkkkkkkko..",".okkkkkkkkkkkkor",".orrrrrrrrrrrror",".okkkkkkkkkkkkr.",".okkwwwwwwwwkko.",".okkwwwwwwwwkko.",".okkkkkkkkkkkko.",".okkkkkkkkkkkko.","..okkkkkkkkkko..","...ookkkkkkoo...",".....oooooo.....","................"},{"................",".....oooooo.....","...ookkkkkkoo...","..okkkkkkkkkko..","..okkkkkkkkkko..",".okkkkkkkkkkkko.",".orrrrrrrrrrrror",".okkkkkkkkkkkkor",".okkwwwwwwwwkkor",".okkwwwwwwwwkko.",".okkkkkkkkkkkko.",".okkkkkkkkkkkko.","..okkkkkkkkkko..","...ookkkkkkoo...",".....oooooo.....","................"}}, "k#2E2E3A,o#111118", new int[]{5,8,9,8}, null, new int[]{13,2}, "k", null, ""},
            {"Hongo", 1, new String[][]{{"................",".....oooooo.....","...oorrrrrroo...","..orrrrwwrrrro..",".orrwwrrrrwwrro.",".orrwwrrrrwwrro.","orrrrrrrrrrrrrro","orrrrrrwwrrrrrro","oooooooooooooooo","..owwwwwwwwwwo..","..owwwwwwwwwwo..","..owwwwwwwwwwo..","..owwwwwwwwwwo..","...oooooooooo...","................","................"}}, "r#E5484D", new int[]{5,9,9,9}, new int[]{6,11}, new int[]{14,1}, "k", null, ""},
            {"Capibara", 7, new String[][]{{"......yyyy......","..oo...yy...oo..",".obbo......obbo.",".obbboooooobbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","..obbddddddbbo..","..obddddddddbo..","..obbbbbbbbbbo..","...oooooooooo...","................","................"}}, "b#B07A4F,d#8A5A38,y#F5A524", new int[]{4,6,10,6}, new int[]{6,11}, new int[]{14,3}, "o", new int[]{6,10}, ""},
            {"Pingüino", 8, new String[][]{{"................",".....oooooo.....","...ookkkkkkoo...","..okkkkkkkkkko..","..okkwwwwwwkko..",".okkwwwwwwwwkko.",".okkwwwwwwwwkko.",".okkwwwwwwwwkko.",".okkwwwwwwwwkko.",".okkwwwyywwwkko.",".okkwwwwwwwwkko.","..okkwwwwwwkko..","..okkkwwwwkkko..","...ookkkkkkoo...","...oyyooooyyo...","................"}}, "k#2B3A55,o#121826", new int[]{5,6,9,6}, null, new int[]{14,2}, "k", null, ""},
            {"Calavera", 2, new String[][]{{"................",".....oooooo.....","...oowwwwwwoo...","..owwwwwwwwwwo..","..owwwwwwwwwwo..",".owwwwwwwwwwwwo.",".owwwwwwwwwwwwo.",".owwwwwwwwwwwwo.",".owwwwwwwwwwwwo.","..owwwwwwwwwwo..","...owwwwwwwwo...","...owowoowowo...","...owwwwwwwwo...","....oooooooo....","................","................"},{"................",".....oooooo.....","...oowwwwwwoo...","..owwwwwwwwwwo..","..owwwwwwwwwwo..",".owwwwwwwwwwwwo.",".owwwwwwwwwwwwo.",".owwwwwwwwwwwwo.",".owwwwwwwwwwwwo.","..owwwwwwwwwwo..","...owwwwwwwwo...","...owowoowowo...","...o...ww...o...","....oooooooo....","................","................"}}, "w#F2EFE6,o#3A3530", new int[]{4,6,10,6}, null, new int[]{14,2}, "k", null, "s"},
    };
}
