package com.matias.claudeusage;

/** Generado desde el diseño de las mascotas (16x16, pixel art). */
final class MascotData {
    static final String[] ANIMS = {"bob","squash","float","cat","robot","march","hover","chill","waddle"};
    static final Object[][] ALL = {
            {"Blob", 0, new String[][]{{"................",".....oooooo.....","...oobbbbbboo...","..obhhbbbbbbbo..","..obhbbbbbbbbo..",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","..obbbbbbbbbbo..","...oobbbbbboo...","....oo....oo....","................"}}, "b#D97757", new int[]{4,6,10,6}, new int[]{6,9}, new int[]{14,1}, "o", null, ""},
            {"Slime", 1, new String[][]{{"................",".......oo.......","......obbo......",".....ohhhbo.....","....ohhbbbbo....","...obhbbbbbbo...","..obhbbbbbbbbo..","..obbbbbbbbbbo..",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".odbbbbbbbbbbdo.","..oddddddddddo..","...oooooooooo...","................"}}, "b#4FA3E8", new int[]{5,8,9,8}, new int[]{6,11}, new int[]{13,3}, "o", null, ""},
            {"Fantasma", 2, new String[][]{{"................",".....oooooo.....","...oobbbbbboo...","..obhbbbbbbbbo..","..ohbbbbbbbbbo..",".obhbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbo.obbo.obbo.","..oo...oo...oo.."},{"................",".....oooooo.....","...oobbbbbboo...","..obhbbbbbbbbo..","..ohbbbbbbbbbo..",".obhbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbo.oo.obbbo.","..ooo......ooo.."}}, "b#E9E4FF,o#3B3366", new int[]{4,7,10,7}, new int[]{6,10}, new int[]{14,2}, "k", null, ""},
            {"Gato", 3, new String[][]{{"................","..o..........o..",".opo........opo.",".opbo......obpo.",".obbboooooobbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","oobbbbbbbbbbbboo",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","...oobbbbbboo...",".....oooooo.....","................","................","................"},{"................",".............o..","............opo.",".oooo......obpo.",".obbboooooobbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","oobbbbbbbbbbbboo",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","...oobbbbbboo...",".....oooooo.....","................","................","................"}}, "b#F2A65A", new int[]{4,6,10,6}, new int[]{6,9}, new int[]{14,4}, "o", new int[]{7,8}, ""},
            {"Robot", 4, new String[][]{{".......rr.......",".......oo.......",".......oo.......",".......oo.......","...oooooooooo...","..ohbbbbbbbbbo..","..ohkkkkkkkkbo..","..obkkkkkkkkbo..","..obkkkkkkkkbo..","..obbbbbbbbbbo..","..obbbbbbbbbbo..","..obbbbbbbbbbo..","..obbbbbbbbbbo..","...oooooooooo...","....obbbbbbo....","....oooooooo...."},{".......yy.......",".......oo.......",".......oo.......",".......oo.......","...oooooooooo...","..ohbbbbbbbbbo..","..ohkkkkkkkkbo..","..obkkkkkkkkbo..","..obkkkkkkkkbo..","..obbbbbbbbbbo..","..obbbbbbbbbbo..","..obbbbbbbbbbo..","..obbbbbbbbbbo..","...oooooooooo...","....obbbbbbo....","....oooooooo...."}}, "b#9AA7B8", new int[]{5,7,9,7}, new int[]{6,10}, new int[]{14,4}, "c", null, ""},
            {"Invasor", 5, new String[][]{{"................","................","................","................","..b..........b..","...b........b...","..bbbbbbbbbbbb..",".bb.bbbbbbbb.bb.","bbbbbbbbbbbbbbbb","b.bbbbbbbbbbbb.b","b.b..........b.b","...bb......bb...","................","................","................","................"},{"................","................","................","................","..b..........b..","...b........b...","b.bbbbbbbbbbbb.b","bbb.bbbbbbbb.bbb","bbbbbbbbbbbbbbbb","..bbbbbbbbbbbb..","................",".bb..........bb.","................","................","................","................"}}, "b#7CF57C", new int[]{3,7,12,7}, null, new int[]{14,3}, "k", null, "n"},
            {"Dragoncito", 6, new String[][]{{"................","...y........y...","..oyo......oyo..","..obboooooobbo..","..obbbbbbbbbbo..",".sbbbbbbbbbbbbs.","sobbbbbbbbbbbbos","sobbbbbbbbbbbbos",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","..obssssssssbo..","...osssssssso...","....oooooooo....","....o..oo..o....","................"},{"................","...y........y...","..oyo......oyo..","..obboooooobbo..","..obbbbbbbbbbo..",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","sobbbbbbbbbbbbos","s.obbbbbbbbbbo.s",".sobssssssssbos.","...osssssssso...","....oooooooo....","....o..oo..o....","................"}}, "b#59C28C,s#F6D186", new int[]{4,6,10,6}, new int[]{6,9}, new int[]{14,3}, "o", null, ""},
            {"Ninja", 0, new String[][]{{"................",".....oooooo.....","...ookkkkkkoo...","..okkkkkkkkkko..","..okkkkkkkkkko..",".okkkkkkkkkkkkor",".orrrrrrrrrrrror",".okkkkkkkkkkkkr.",".okkwwwwwwwwkko.",".okkwwwwwwwwkko.",".okkkkkkkkkkkko.",".okkkkkkkkkkkko.","..okkkkkkkkkko..","...ookkkkkkoo...",".....oooooo.....","................"},{"................",".....oooooo.....","...ookkkkkkoo...","..okkkkkkkkkko..","..okkkkkkkkkko..",".okkkkkkkkkkkko.",".orrrrrrrrrrrror",".okkkkkkkkkkkkor",".okkwwwwwwwwkkor",".okkwwwwwwwwkko.",".okkkkkkkkkkkko.",".okkkkkkkkkkkko.","..okkkkkkkkkko..","...ookkkkkkoo...",".....oooooo.....","................"}}, "k#2E2E3A,o#111118", new int[]{5,8,9,8}, null, new int[]{13,2}, "k", null, ""},
            {"Hongo", 1, new String[][]{{"................",".....oooooo.....","...oorrrrrroo...","..orrrrwwrrrro..",".orrwwrrrrwwrro.",".orrwwrrrrwwrro.","orrrrrrrrrrrrrro","orrrrrrwwrrrrrro","oooooooooooooooo","..owwwwwwwwwwo..","..owwwwwwwwwwo..","..owwwwwwwwwwo..","..owwwwwwwwwwo..","...oooooooooo...","................","................"}}, "r#E5484D", new int[]{5,9,9,9}, new int[]{6,11}, new int[]{14,1}, "k", null, ""},
            {"Capibara", 7, new String[][]{{"......yyyy......","..oo...yy...oo..",".obbo......obbo.",".obbboooooobbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","..obbddddddbbo..","..obddddddddbo..","..obbbbbbbbbbo..","...oooooooooo...","................","................"}}, "b#B07A4F,d#8A5A38,y#F5A524", new int[]{4,6,10,6}, new int[]{6,11}, new int[]{14,3}, "o", new int[]{6,10}, ""},
            {"Pingüino", 8, new String[][]{{"................",".....oooooo.....","...ookkkkkkoo...","..okkkkkkkkkko..","..okkwwwwwwkko..",".okkwwwwwwwwkko.",".okkwwwwwwwwkko.",".okkwwwwwwwwkko.",".okkwwwwwwwwkko.",".okkwwwyywwwkko.",".okkwwwwwwwwkko.","..okkwwwwwwkko..","..okkkwwwwkkko..","...ookkkkkkoo...","...oyyooooyyo...","................"}}, "k#2B3A55,o#121826", new int[]{5,6,9,6}, null, new int[]{14,2}, "k", null, ""},
            {"Calavera", 2, new String[][]{{"................",".....oooooo.....","...oowwwwwwoo...","..owwwwwwwwwwo..","..owwwwwwwwwwo..",".owwwwwwwwwwwwo.",".owwwwwwwwwwwwo.",".owwwwwwwwwwwwo.",".owwwwwwwwwwwwo.","..owwwwwwwwwwo..","...owwwwwwwwo...","...owowoowowo...","...owwwwwwwwo...","....oooooooo....","................","................"},{"................",".....oooooo.....","...oowwwwwwoo...","..owwwwwwwwwwo..","..owwwwwwwwwwo..",".owwwwwwwwwwwwo.",".owwwwwwwwwwwwo.",".owwwwwwwwwwwwo.",".owwwwwwwwwwwwo.","..owwwwwwwwwwo..","...owwwwwwwwo...","...owowoowowo...","...o...ww...o...","....oooooooo....","................","................"}}, "w#F2EFE6,o#3A3530", new int[]{4,6,10,6}, null, new int[]{14,2}, "k", null, "s"},
            {"Perro", 0, new String[][]{{"................","................","....oooooooo....","..oobbbbbbbboo..",".oddobbbbbboddo.","oddddobbbboddddo","oddddbbbbbbddddo","oddddbbbbbbddddo",".oddbbbbbbbbddo.","..obbbbbbbbbbo..","..obbwwkkwwbbo..","..obwwwwwwwwbo..","...owwwwwwwwo...","....oooooooo....","................","................"}}, "b#C8915A,d#7A4E2D,w#F4E6D0", new int[]{5,7,9,7}, new int[]{6,11}, new int[]{14,2}, "o", null, ""},
            {"Gato negro", 3, new String[][]{{"................","..o..........o..",".opo........opo.",".opbo......obpo.",".obbboooooobbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","oobbbbbbbbbbbboo",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","...oobbbbbboo...",".....oooooo.....","................","................","................"},{"................",".............o..","............opo.",".oooo......obpo.",".obbboooooobbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","oobbbbbbbbbbbboo",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","...oobbbbbboo...",".....oooooo.....","................","................","................"}}, "b#34343F,o#15151B", new int[]{4,6,10,6}, new int[]{6,9}, new int[]{14,4}, "y", new int[]{7,8}, ""},
            {"Loro", 6, new String[][]{{"................",".....oooooo.....","....obbbbbbo....","...obhbbbbhbo...","..obbbbbbbbbbo..","..obbbbbbbbbbo..",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbyyyybbbbo.",".obbbbyyyybbbbo.",".obbbbbkkbbbbbo.","..orrbbbbbbrro..","..orrrbbbbrrro..","...oooooooooo...","................"},{"................",".....oooooo.....","....obbbbbbo....","...obhbbbbhbo...","..obbbbbbbbbbo..","..obbbbbbbbbbo..",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".rbbbbbbbbbbbbr.",".rbbbbyyyybbbbr.",".rbbbbyyyybbbbr.",".obbbbbkkbbbbbo.","..orrbbbbbbrro..","..orrrbbbbrrro..","...oooooooooo...","................"}}, "b#3BB273,y#F5B700,r#E84855", new int[]{4,6,10,6}, null, new int[]{14,1}, "o", null, ""},
            {"Hámster", 1, new String[][]{{"................","................","..oo........oo..",".oppooooooooppo.",".obbbbbbbbbbbbo.","obbbbbbbbbbbbbbo","obbbbbbbbbbbbbbo","obbbbbbbbbbbbbbo","obbbbwwwwwwbbbbo","obbbwwwwwwwwbbbo","obbwwwwwwwwwwbbo",".obwwwwwwwwwwbo.","..owwwwwwwwwwo..","...oooooooooo...","................","................"}}, "b#E8A15C,w#FFF3E0", new int[]{4,6,10,6}, new int[]{6,10}, new int[]{14,2}, "o", new int[]{7,9}, ""},
            {"Pez", 2, new String[][]{{"................","................","....oooooo......","...obbwbbbo...o.","..obhbwbbbbo.obo",".obbbbwbbbbbobbo",".obbbbwbbbbbbbbo",".obbbbwbbbbbbbbo",".obbbbwbbbbbbbbo",".obbbbwbbbbbobbo","..obbbwbbbbo.obo","...obbwbbbo...o.","....oooooo......","................","................","................"},{"................","................","....oooooo......","...obbwbbbo.....","..obhbwbbbbo..oo",".obbbbwbbbbbooob",".obbbbwbbbbbbbbo",".obbbbwbbbbbbbbo",".obbbbwbbbbbbbbo",".obbbbwbbbbbooob","..obbbwbbbbo..oo","...obbwbbbo.....","....oooooo......","................","................","................"}}, "b#FF8C42", new int[]{3,6,8,6}, new int[]{3,9}, new int[]{13,1}, "k", null, ""},
            {"Fontanero rojo", 0, new String[][]{{".....oooooo.....","....oaaaaaao....","...oaaawwaaao...","..oaaaawwaaaao..",".oaaaaaaaaaaaao.",".okkbbbbbbbbkko.","okkbbbbbbbbbbkko","okbbbbbbbbbbbbko","okbbbbbbbbbbbbko",".obbbbbnnbbbbbo.",".obbkkkkkkkkbbo.","..obbbbbbbbbbo..","..oobbbbbbbboo..",".oaavvvvvvvvaao.","oaaavyvvvvyvaaao","oaavvvvvvvvvvaao"}}, "b#F2C9A0,a#E52521,k#5B3A1E,v#2B4FD1,y#F5C542,n#D99A6C,w#FFFFFF,o#2A1A12", new int[]{5,7,9,7}, null, new int[]{14,1}, "k", null, ""},
            {"Fontanero verde", 0, new String[][]{{".....oooooo.....","....oaaaaaao....","...oaaawwaaao...","..oaaaawwaaaao..",".oaaaaaaaaaaaao.",".okkbbbbbbbbkko.","okkbbbbbbbbbbkko","okbbbbbbbbbbbbko","okbbbbbbbbbbbbko",".obbbbbnnbbbbbo.",".obbkkkkkkkkbbo.","..obbbbbbbbbbo..","..oobbbbbbbboo..",".oaavvvvvvvvaao.","oaaavyvvvvyvaaao","oaavvvvvvvvvvaao"}}, "b#F2C9A0,a#2FAE4E,k#5B3A1E,v#2B4FD1,y#F5C542,n#D99A6C,w#FFFFFF,o#14241A", new int[]{5,7,9,7}, null, new int[]{14,1}, "k", null, ""},
            {"Erizo azul", 6, new String[][]{{".obo...oo...obo.",".obbo.obbo.obbo.",".obbbobbbbobbbo.","obbbbbbbbbbbbbbo","bbbbbbbbbbbbbbbb","obbbbbbbbbbbbbbo","bbbbwwwwwwwwbbbb","obbbwwwwwwwwbbbo","bbbbwwwwwwwwbbbb","obbbbmmkkmmbbbbo",".obbmmmmmmmmbbo.",".obbmmmmmmmmbbo.","..obbmmmmmmbbo..","...obbbbbbbbo...","....oooooooo....","................"}}, "b#1E5BD8,w#FFFFFF,m#F3C892,k#151515,o#0B1F4D", new int[]{5,7,9,7}, new int[]{6,11}, new int[]{14,1}, "k", null, ""},
            {"Ranger rojo", 0, new String[][]{{".....oooooo.....","....oaaaaaao....","...oaaaaaaaao...","..oaaaaaaaaaao..",".oaaaaaaaaaaaao.","oaaakkkkkkkkaaao","oaakkkkkkkkkkaao","oaakkkkkkkkkkaao","oaaakkkkkkkkaaao","oaaaakkkkkkaaaao","oaaaaaakkaaaaaao",".oaaaaggggaaaao.","..oaaaggggaaao..",".owwaaaaaaaawwo.","oaaawwaaaawwaaao","oaaaaaaaaaaaaaao"}}, "b#E53935,a#E53935,k#111116,g#B8C0CC,w#FFFFFF,c#7FF7FF,o#141418", new int[]{5,7,9,7}, null, new int[]{14,1}, "c", null, ""},
            {"Ranger azul", 0, new String[][]{{".....oooooo.....","....oaaaaaao....","...oaaaaaaaao...","..oaaaaaaaaaao..",".oaaaaaaaaaaaao.","oaaakkkkkkkkaaao","oaakkkkkkkkkkaao","oaakkkkkkkkkkaao","oaaakkkkkkkkaaao","oaaaakkkkkkaaaao","oaaaaaakkaaaaaao",".oaaaaggggaaaao.","..oaaaggggaaao..",".owwaaaaaaaawwo.","oaaawwaaaawwaaao","oaaaaaaaaaaaaaao"}}, "b#1E88E5,a#1E88E5,k#111116,g#B8C0CC,w#FFFFFF,c#7FF7FF,o#141418", new int[]{5,7,9,7}, null, new int[]{14,1}, "c", null, ""},
            {"Ranger rosa", 0, new String[][]{{".....oooooo.....","....oaaaaaao....","...oaaaaaaaao...","..oaaaaaaaaaao..",".oaaaaaaaaaaaao.","oaaakkkkkkkkaaao","oaakkkkkkkkkkaao","oaakkkkkkkkkkaao","oaaakkkkkkkkaaao","oaaaakkkkkkaaaao","oaaaaaakkaaaaaao",".oaaaaggggaaaao.","..oaaaggggaaao..",".owwaaaaaaaawwo.","oaaawwaaaawwaaao","oaaaaaaaaaaaaaao"}}, "b#EC407A,a#EC407A,k#111116,g#B8C0CC,w#FFFFFF,c#7FF7FF,o#141418", new int[]{5,7,9,7}, null, new int[]{14,1}, "c", null, ""},
            {"Ranger amarillo", 0, new String[][]{{".....oooooo.....","....oaaaaaao....","...oaaaaaaaao...","..oaaaaaaaaaao..",".oaaaaaaaaaaaao.","oaaakkkkkkkkaaao","oaakkkkkkkkkkaao","oaakkkkkkkkkkaao","oaaakkkkkkkkaaao","oaaaakkkkkkaaaao","oaaaaaakkaaaaaao",".oaaaaggggaaaao.","..oaaaggggaaao..",".owwaaaaaaaawwo.","oaaawwaaaawwaaao","oaaaaaaaaaaaaaao"}}, "b#FDD835,a#FDD835,k#111116,g#B8C0CC,w#FFFFFF,c#7FF7FF,o#141418", new int[]{5,7,9,7}, null, new int[]{14,1}, "c", null, ""},
            {"Ranger verde", 0, new String[][]{{".....oooooo.....","....oaaaaaao....","...oaaaaaaaao...","..oaaaaaaaaaao..",".oaaaaaaaaaaaao.","oaaakkkkkkkkaaao","oaakkkkkkkkkkaao","oaakkkkkkkkkkaao","oaaakkkkkkkkaaao","oaaaakkkkkkaaaao","oaaaaaakkaaaaaao",".oaaaaggggaaaao.","..oaaaggggaaao..",".owwaaaaaaaawwo.","oaaawwaaaawwaaao","oaaaaaaaaaaaaaao"}}, "b#43A047,a#43A047,k#111116,g#B8C0CC,w#FFFFFF,c#7FF7FF,o#141418", new int[]{5,7,9,7}, null, new int[]{14,1}, "c", null, ""},
            {"Ranger negro", 0, new String[][]{{".....oooooo.....","....oaaaaaao....","...oaaaaaaaao...","..oaaaaaaaaaao..",".oaaaaaaaaaaaao.","oaaakkkkkkkkaaao","oaakkkkkkkkkkaao","oaakkkkkkkkkkaao","oaaakkkkkkkkaaao","oaaaakkkkkkaaaao","oaaaaaakkaaaaaao",".oaaaaggggaaaao.","..oaaaggggaaao..",".owwaaaaaaaawwo.","oaaawwaaaawwaaao","oaaaaaaaaaaaaaao"}}, "b#3A3A44,a#3A3A44,k#111116,g#B8C0CC,w#FFFFFF,c#7FF7FF,o#141418", new int[]{5,7,9,7}, null, new int[]{14,1}, "c", null, ""},
            {"Minero cúbico", 0, new String[][]{{"..oooooooooooo..",".okkkkkkkkkkkko.",".okkkkkkkkkkkko.",".okbbbbbbbbbbko.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbwbbbbbbwbbo.",".obbwbbbbbbwbbo.",".obbbbbnnbbbbbo.",".obbbnnnnnnbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".occcccccccccco.",".occcccccccccco.",".occcccccccccco."}}, "b#C9926B,k#3B2615,n#7A4A30,w#FFFFFF,c#00A6A6,o#1C130C,v#4A3B9C", new int[]{5,7,9,7}, null, new int[]{14,1}, "v", null, ""},
            {"Minera cúbica", 0, new String[][]{{"..oooooooooooo..",".okkkkkkkkkkkko.",".okkkkkkkkkkkko.",".okkkkkkbbbbkko.",".obbbbbbbbbbkbo.",".obbbbbbbbbbkbo.",".obbbbbbbbbbkbo.",".obbwbbbbbbwkbo.",".obbwbbbbbbwkbo.",".obbbbbnnbbbkbo.",".obbbnnnnnnbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".occcccccccccco.",".occcccccccccco.",".occcccccccccco."}}, "b#E8B08A,k#D86A1E,n#B57454,w#FFFFFF,c#5FA34F,v#2E8B57,o#2A160A", new int[]{5,7,9,7}, null, new int[]{14,1}, "v", null, ""},
            {"Explosivo verde", 1, new String[][]{{".obhhbbhdhbhbdo.",".obhbbdhhddbbbo.",".ohdbbbhbbbbdho.",".odddhdbbbbbdbo.",".obdkkhdhbkkdho.",".obbkkhbbhkkbbo.",".ohbbbbkkbbbdbo.",".obbddkkkkbdhbo.",".ohbhbkkkkbhhbo.",".obdbhkbbkbbbdo.",".oddhdhhbhhbdbo.",".obdbhbhbbdhbbo.",".odhhbbbdbbhbdo.",".obhbbbbdbhhbbo.",".obbbbhbbdbbhbo.",".obhbbbbbdbbhbo."}}, "b#5BBA47,d#3E8C2F,h#8FD67E,k#101010,o#1A2E14", new int[]{4,4,10,4}, null, new int[]{14,0}, "k", null, "n"},
            {"Comecocos", 5, new String[][]{{"................","....oooooo......","...oyyyyyyo.....","..oyyyyyyyyo....",".oyyykyyyyyyo...",".oyyyyyyyyo.....",".oyyyyyyyo......",".oyyyyyyo.......",".oyyyyyyyo......",".oyyyyyyyyo.....",".oyyyyyyyyyyo...","..oyyyyyyyyo....","...oyyyyyyo.....","....oooooo......","................","................"},{"................","....oooooo......","...oyyyyyyo.....","..oyyyyyyyyo....",".oyyykyyyyyyo...",".oyyyyyyyyyyo...",".oyyyyyyyyyyyo..",".oyyyyyyyyyyyo..",".oyyyyyyyyyyyo..",".oyyyyyyyyyyo...",".oyyyyyyyyyyo...","..oyyyyyyyyo....","...oyyyyyyo.....","....oooooo......","................","................"}}, "b#FFD300,y#FFD300,k#111111,o#7A5A00", new int[]{4,4,8,4}, null, new int[]{11,1}, "k", null, "n"},
            {"Bola rosa", 1, new String[][]{{"................","................","....oooooooo....","...obbbbbbbbo...","..obhbbbbbbbbo..",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","..orrrobborrro..","..orrrroorrrro..","...oooo..oooo...","................","................"}}, "b#F7A8C8,r#E0315A,o#7A2747", new int[]{5,6,9,6}, new int[]{6,9}, new int[]{14,1}, "k", null, ""},
            {"Héroe del bosque", 0, new String[][]{{"...........oo...","..........oggo..","......oooogggo..","....oogggggggo..","...oggggggggo...","..ogggggggggo...",".oyyyyyyyyyyyo..",".oybbbbbbbbbyo..","oobbbbbbbbbbboo.","obbbbbbbbbbbbbo.",".obbbbbbbbbbbo..","..obbbbbbbbbo...","..oobbbbbbboo...",".ogggggggggggo..","ogggggkkggggggo.","oggggggggggggggo"}}, "b#F2C9A0,g#2E9E44,y#F2D16B,k#6B4226,o#14301A,v#2B5FD9", new int[]{4,8,9,8}, new int[]{5,11}, new int[]{14,1}, "v", null, ""},
            {"Robot azul", 0, new String[][]{{".....oooooo.....","...ooaaaaaaoo...","..oaaaaaaaaaao..",".oaaaaaccaaaaao.",".oaaaaccccaaaao.","oaaabbbbbbbbaaao","oaabbbbbbbbbbaao","oaabbbbbbbbbbaao","oaabbbbbbbbbbaao","oaabbbbbbbbbbaao",".oabbbbbbbbbbao.","..obbbbbbbbbbo..","..oobbbbbbbboo..",".oaaaaaaaaaaaao.","oacaaaaaaaaaacao","oaaaaaaaaaaaaaao"}}, "b#F2C9A0,a#1E6FE0,c#5EC8FF,o#0C1E40,v#1E6FE0", new int[]{5,7,9,7}, new int[]{6,10}, new int[]{14,1}, "v", null, ""},
            {"Dinosaurio verde", 6, new String[][]{{"................","....oooo........","...obbbbo.......","..owwbbwwo......","..owkbbwko......","..obbbbbbbooo...","..obbbbbbbbbbo..","..obbbbbbbbbbbo.","..obbbbbbbbbbbo.","..obbbbbbbbbbo..","..owwwwwwwwwo...","..owwwwwwwwo....","...obbbbbbo.....","...orrroorro....","....ooo..ooo....","................"}}, "b#5BC236,w#FFFFFF,k#111111,r#E0471F,o#1D3D12", new int[]{3,3,7,3}, new int[]{5,9}, new int[]{13,1}, "k", null, "n"},
            {"Espada", 8, new String[][]{{".......oo.......","......owgo......","......owgo......","......owgo......","......owgo......","......owgo......","......owgo......","......owgo......","......owgo......","...oooooooooo...","...oyyyyyyyyo...","...oooooooooo...","......okko......","......okko......",".....oyyyyo.....","......oooo......"}}, "b#9AA7B3,w#E8EEF2,g#9AA7B3,y#F5C542,k#6B4226,o#2B2B33", new int[]{5,4,9,4}, null, new int[]{13,1}, "o", null, "n"},
            {"Hacha", 8, new String[][]{{"................",".........oo.....","...ooooookko....","..ohwwwwwkko....",".ohwwwwwwkko....",".ohwwwwwwkko....",".ohwwwwwwkko....","..ohwwwwwkko....","...ooooookko....","........okko....","........okko....","........okko....","........okko....","........okko....","........okko....","........oooo...."}}, "b#9AA7B3,w#B9C4CE,h#EEF3F7,k#7A4A24,o#2B2B33", new int[]{3,4,6,4}, null, new int[]{13,1}, "o", null, "n"},
            {"Arco y flecha", 0, new String[][]{{"................",".....kw.........","....k.w.........","...k..w.........","...k..w.........","..k...w.........","..k...w......g..","..kryyyyyyyyyggg","..k...w......g..","..k...w.........","...k..w.........","...k..w.........","....k.w.........",".....kw.........","................","................"},{"................",".....k..........","....k.w.........","...k...w........","...k....w.......","..k......w......","..k......w...g..","..kr.....wyyyggg","..k......w...g..","..k......w......","...k....w.......","...k...w........","....k.w.........",".....k..........","................","................"}}, "b#8B5A2B,k#8B5A2B,w#EDEDED,y#D9B07A,g#9AA7B3,r#E84855", new int[]{3,4,6,4}, null, new int[]{13,1}, "o", null, "n"},
    };
    static final String[] CAT_NAMES = {"Clásicas","Animales","Juegos y cultura","Armas medievales"};
    static final int[][] CATS = {{0,1,2,3,4,5,6,7,8,9,10,11},{12,13,14,15,16},{17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33},{34,35,36}};
    static final String[] KEYS = {"blob","slime","ghost","cat","robot","invader","dragon","ninja","mush","capy","penguin","skull","dog","blackcat","parrot","hamster","fish","plumber_r","plumber_g","hedgehog","ranger_r","ranger_b","ranger_p","ranger_y","ranger_g","ranger_k","miner","minerf","creeper","pac","puff","elf","bluebot","dino","sword","axe","bow"};
}
