package com.matias.claudeusage;

/** Generado desde el diseño de las mascotas (16x16, pixel art). */
final class MascotData {
    static final String[] ANIMS = {"bob","squash","float","cat","robot","march","hover","chill","waddle"};
    static final Object[][] ALL = {
            {"Blob", 0, new String[][]{{"................",".....oooooo.....","...oobbbbbboo...","..obhhbbbbbbbo..","..obhbbbbbbbbo..",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","..obbbbbbbbbbo..","...oobbbbbboo...","....oo....oo....","................"}}, "b#D97757", new int[]{4,6,10,6}, new int[]{6,9}, new int[]{14,1}, "o", null, ""},
            {"Slime", 1, new String[][]{{"................",".......oo.......","......obbo......",".....ohhhbo.....","....ohhbbbbo....","...obhbbbbbbo...","..obhbbbbbbbbo..","..obbbbbbbbbbo..",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".odbbbbbbbbbbdo.","..oddddddddddo..","...oooooooooo...","................"}}, "b#4FA3E8", new int[]{5,8,9,8}, new int[]{6,11}, new int[]{13,3}, "o", null, ""},
            {"Fantasma", 2, new String[][]{{"................",".....oooooo.....","...oobbbbbboo...","..obhbbbbbbbbo..","..ohbbbbbbbbbo..",".obhbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbo.obbo.obbo.","..oo...oo...oo.."},{"................",".....oooooo.....","...oobbbbbboo...","..obhbbbbbbbbo..","..ohbbbbbbbbbo..",".obhbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbo.oo.obbbo.","..ooo......ooo.."}}, "b#E9E4FF,o#3B3366", new int[]{4,7,10,7}, new int[]{6,10}, new int[]{14,2}, "k", null, ""},
            {"Gato", 3, new String[][]{{"................","..o..........o..",".opo........opo.",".opbo......obpo.",".obbboooooobbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","oobbbbbbbbbbbboo",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","...oobbbbbboo...",".....oooooo.....","................","................","................"},{"................",".............o..","............opo.",".oooo......obpo.",".obbboooooobbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","oobbbbbbbbbbbboo",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","...oobbbbbboo...",".....oooooo.....","................","................","................"}}, "b#F2A65A", new int[]{4,6,10,6}, new int[]{6,9}, new int[]{14,4}, "o", new int[]{7,8}, ""},
            {"Robot", 4, new String[][]{{".......rr.......",".......oo.......",".......oo.......",".......oo.......","...oooooooooo...","..ohbbbbbbbbbo..","..ohkkkkkkkkbo..","..obkkkkkkkkbo..","..obkkkkkkkkbo..","..obbbbbbbbbbo..","..obbbbbbbbbbo..","..obbbbbbbbbbo..","..obbbbbbbbbbo..","...oooooooooo...","....obbbbbbo....","....oooooooo...."},{".......yy.......",".......oo.......",".......oo.......",".......oo.......","...oooooooooo...","..ohbbbbbbbbbo..","..ohkkkkkkkkbo..","..obkkkkkkkkbo..","..obkkkkkkkkbo..","..obbbbbbbbbbo..","..obbbbbbbbbbo..","..obbbbbbbbbbo..","..obbbbbbbbbbo..","...oooooooooo...","....obbbbbbo....","....oooooooo...."}}, "b#9AA7B8", new int[]{5,7,9,7}, new int[]{6,10}, new int[]{14,4}, "c", null, ""},
            {"Invasor", 5, new String[][]{{"................","................","................","................","..b..........b..","...b........b...","..bbbbbbbbbbbb..",".bb.bbbbbbbb.bb.","bbbbbbbbbbbbbbbb","b.bbbbbbbbbbbb.b","b.b..........b.b","...bb......bb...","................","................","................","................"},{"................","................","................","................","..b..........b..","...b........b...","b.bbbbbbbbbbbb.b","bbb.bbbbbbbb.bbb","bbbbbbbbbbbbbbbb","..bbbbbbbbbbbb..","................",".bb..........bb.","................","................","................","................"}}, "b#7CF57C", new int[]{3,7,12,7}, null, new int[]{14,3}, "k", null, "n"},
            {"Dragoncito", 6, new String[][]{{"................","...y........y...","..oyo......oyo..","..obboooooobbo..","..obbbbbbbbbbo..",".sbbbbbbbbbbbbs.","sobbbbbbbbbbbbos","sobbbbbbbbbbbbos",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","..obssssssssbo..","...osssssssso...","....oooooooo....","....o..oo..o....","................"},{"................","...y........y...","..oyo......oyo..","..obboooooobbo..","..obbbbbbbbbbo..",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","sobbbbbbbbbbbbos","s.obbbbbbbbbbo.s",".sobssssssssbos.","...osssssssso...","....oooooooo....","....o..oo..o....","................"}}, "b#59C28C,s#F6D186", new int[]{4,6,10,6}, new int[]{6,9}, new int[]{14,3}, "o", null, ""},
            {"Ninja", 0, new String[][]{{"................",".....oooooo.....","...ookkkkkkoo...","..okkkkkkkkkko..","..okkkkkkkkkko..",".okkkkkkkkkkkkor",".orrrrrrrrrrrror",".okkkkkkkkkkkkr.",".okkwwwwwwwwkko.",".okkwwwwwwwwkko.",".okkkkkkkkkkkko.",".okkkkkkkkkkkko.","..okkkkkkkkkko..","...ookkkkkkoo...",".....oooooo.....","................"},{"................",".....oooooo.....","...ookkkkkkoo...","..okkkkkkkkkko..","..okkkkkkkkkko..",".okkkkkkkkkkkko.",".orrrrrrrrrrrror",".okkkkkkkkkkkkor",".okkwwwwwwwwkkor",".okkwwwwwwwwkko.",".okkkkkkkkkkkko.",".okkkkkkkkkkkko.","..okkkkkkkkkko..","...ookkkkkkoo...",".....oooooo.....","................"}}, "k#2E2E3A,o#111118", new int[]{5,8,9,8}, null, new int[]{13,2}, "k", null, ""},
            {"Hongo", 1, new String[][]{{"................",".....oooooo.....","...oorrrrrroo...","..orrrrwwrrrro..",".orrwwrrrrwwrro.",".orrwwrrrrwwrro.","orrrrrrrrrrrrrro","orrrrrrwwrrrrrro","oooooooooooooooo","..owwwwwwwwwwo..","..owwwwwwwwwwo..","..owwwwwwwwwwo..","..owwwwwwwwwwo..","...oooooooooo...","................","................"}}, "r#E5484D", new int[]{5,9,9,9}, new int[]{6,11}, new int[]{14,1}, "k", null, ""},
            {"Capibara", 7, new String[][]{{"......yyyy......","..oo...yy...oo..",".obbo......obbo.",".obbboooooobbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","..obbddddddbbo..","..obddddddddbo..","..obbbbbbbbbbo..","...oooooooooo...","................","................"}}, "b#B07A4F,d#8A5A38,y#F5A524", new int[]{4,6,10,6}, new int[]{6,11}, new int[]{14,3}, "o", new int[]{6,10}, ""},
            {"Pingüino", 8, new String[][]{{"................",".....oooooo.....","...ookkkkkkoo...","..okkkkkkkkkko..","..okkwwwwwwkko..",".okkwwwwwwwwkko.",".okkwwwwwwwwkko.",".okkwwwwwwwwkko.",".okkwwwwwwwwkko.",".okkwwwyywwwkko.",".okkwwwwwwwwkko.","..okkwwwwwwkko..","..okkkwwwwkkko..","...ookkkkkkoo...","...oyyooooyyo...","................"}}, "k#2B3A55,o#121826", new int[]{5,6,9,6}, null, new int[]{14,2}, "k", null, ""},
            {"Calavera", 2, new String[][]{{"................",".....oooooo.....","...oowwwwwwoo...","..owwwwwwwwwwo..","..owwwwwwwwwwo..",".owwwwwwwwwwwwo.",".owwwwwwwwwwwwo.",".owwwwwwwwwwwwo.",".owwwwwwwwwwwwo.","..owwwwwwwwwwo..","...owwwwwwwwo...","...owowoowowo...","...owwwwwwwwo...","....oooooooo....","................","................"},{"................",".....oooooo.....","...oowwwwwwoo...","..owwwwwwwwwwo..","..owwwwwwwwwwo..",".owwwwwwwwwwwwo.",".owwwwwwwwwwwwo.",".owwwwwwwwwwwwo.",".owwwwwwwwwwwwo.","..owwwwwwwwwwo..","...owwwwwwwwo...","...owowoowowo...","...o...ww...o...","....oooooooo....","................","................"}}, "w#F2EFE6,o#3A3530", new int[]{4,6,10,6}, null, new int[]{14,2}, "k", null, "s"},
            {"Perro", 0, new String[][]{{"................","................","....oooooooo....","..oobbbbbbbboo..",".oddobbbbbboddo.","oddddobbbboddddo","oddddbbbbbbddddo","oddddbbbbbbddddo",".oddbbbbbbbbddo.","..obbbbbbbbbbo..","..obbwwkkwwbbo..","..obwwwwwwwwbo..","...owwwwwwwwo...","....oooooooo....","................","................"}}, "b#C8915A,d#7A4E2D,w#F4E6D0", new int[]{5,7,9,7}, new int[]{6,11}, new int[]{14,2}, "o", null, ""},
            {"Gato negro", 3, new String[][]{{"................","..o..........o..",".opo........opo.",".opbo......obpo.",".obbboooooobbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","oobbbbbbbbbbbboo",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","...oobbbbbboo...",".....oooooo.....","................","................","................"},{"................",".............o..","............opo.",".oooo......obpo.",".obbboooooobbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","oobbbbbbbbbbbboo",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","...oobbbbbboo...",".....oooooo.....","................","................","................"}}, "b#34343F,o#15151B", new int[]{4,6,10,6}, new int[]{6,9}, new int[]{14,4}, "y", new int[]{7,8}, ""},
            {"Loro", 6, new String[][]{{"................",".....oooooo.....","....obbbbbbo....","...obhbbbbhbo...","..obbbbbbbbbbo..","..obbbbbbbbbbo..",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbyyyybbbbo.",".obbbbyyyybbbbo.",".obbbbbkkbbbbbo.","..orrbbbbbbrro..","..orrrbbbbrrro..","...oooooooooo...","................"},{"................",".....oooooo.....","....obbbbbbo....","...obhbbbbhbo...","..obbbbbbbbbbo..","..obbbbbbbbbbo..",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".rbbbbbbbbbbbbr.",".rbbbbyyyybbbbr.",".rbbbbyyyybbbbr.",".obbbbbkkbbbbbo.","..orrbbbbbbrro..","..orrrbbbbrrro..","...oooooooooo...","................"}}, "b#3BB273,y#F5B700,r#E84855", new int[]{4,6,10,6}, null, new int[]{14,1}, "o", null, ""},
            {"Hámster", 1, new String[][]{{"................","................","..oo........oo..",".oppooooooooppo.",".obbbbbbbbbbbbo.","obbbbbbbbbbbbbbo","obbbbbbbbbbbbbbo","obbbbbbbbbbbbbbo","obbbbwwwwwwbbbbo","obbbwwwwwwwwbbbo","obbwwwwwwwwwwbbo",".obwwwwwwwwwwbo.","..owwwwwwwwwwo..","...oooooooooo...","................","................"}}, "b#E8A15C,w#FFF3E0", new int[]{4,6,10,6}, new int[]{6,10}, new int[]{14,2}, "o", new int[]{7,9}, ""},
            {"Pez", 2, new String[][]{{"................","................","....oooooo......","...obbwbbbo...o.","..obhbwbbbbo.obo",".obbbbwbbbbbobbo",".obbbbwbbbbbbbbo",".obbbbwbbbbbbbbo",".obbbbwbbbbbbbbo",".obbbbwbbbbbobbo","..obbbwbbbbo.obo","...obbwbbbo...o.","....oooooo......","................","................","................"},{"................","................","....oooooo......","...obbwbbbo.....","..obhbwbbbbo..oo",".obbbbwbbbbbooob",".obbbbwbbbbbbbbo",".obbbbwbbbbbbbbo",".obbbbwbbbbbbbbo",".obbbbwbbbbbooob","..obbbwbbbbo..oo","...obbwbbbo.....","....oooooo......","................","................","................"}}, "b#FF8C42", new int[]{3,6,8,6}, new int[]{3,9}, new int[]{13,1}, "k", null, ""},
            {"Constructor", 0, new String[][]{{"................","......oooo......","....oaaaaaao....","...oaaaaaaaao...","..oaaaaaaaaaao..","oooooooooooooooo",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","...oobbbbbboo...",".....oooooo.....","..ovvvvvvvvvvo..",".ovvvvvvvvvvvvo.",".ovvvvvvvvvvvvo."}}, "b#F2C9A0,a#F5C542,v#E07A1F", new int[]{5,7,9,7}, new int[]{6,10}, new int[]{14,5}, "k", null, ""},
            {"Ingeniero", 0, new String[][]{{"................","......oooo......","....oaaaaaao....","...oaaaaaaaao...","..oaaaaaaaaaao..","oooooooooooooooo",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","...oobbbbbboo...",".....oooooo.....","..ovvvvvvvvvvo..",".ovvvvwwwwvvvvo.",".ovvvvwwwwvvvvo."}}, "b#F2C9A0,a#F2F2F2,v#F28C28,w#DADADA", new int[]{5,7,9,7}, new int[]{6,10}, new int[]{14,5}, "k", null, ""},
            {"Arquitecto", 0, new String[][]{{"................","........a.......","....aaaaaaaa....","..aaaaaaaaaaaa..",".aaaaaaaaaaaaaa.","..obbbbbbbbbbo..",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","...oobbbbbboo...",".....oooooo.....","..ovvvvvvvvvvo..",".ovvvvvvvvvvvvo.",".ovvvvvvvvvvvvo."}}, "b#F2C9A0,a#22222A,v#3A3A48", new int[]{5,7,9,7}, new int[]{6,10}, new int[]{14,5}, "k", null, ""},
            {"Nadador", 0, new String[][]{{"................","................","................","...oaaaaaaaao...","..oaaaaaaaaaao..",".oaaaaaaaaaaaao.",".okllkkkkkkllko.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","...oobbbbbboo...",".....oooooo.....","..obbbbbbbbbbo..",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo."}}, "b#F2C9A0,a#2F80ED,l#7FE7F2,k#1E1E24", new int[]{5,7,9,7}, new int[]{6,10}, new int[]{14,5}, "k", null, ""},
            {"Pescador", 0, new String[][]{{"................","................","....oaaaaaao....","...oaaaaaaaao...","..oaaaaaaaaaao..","oaaaaaaaaaaaaaao",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","...oobbbbbboo...",".....oooooo.....","..ovvvvvvvvvvo..",".ovvvvvvvvvvvvo.",".ovvvvvvvvvvvvo."}}, "b#F2C9A0,a#5B8C4A,v#2D5D7B", new int[]{5,7,9,7}, new int[]{6,10}, new int[]{14,5}, "k", null, ""},
            {"Herrero", 0, new String[][]{{"................","................","................","...oaaaaaaaao...","..oaaaaaaaaaao..",".oaaaaaaaaaaaao.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","...okkbbbbkko...","....okkkkkko....","..ovvvvvvvvvvo..",".ovvvvvvvvvvvvo.",".ovvvvvvvvvvvvo."}}, "b#F2C9A0,a#C0392B,k#4A2E1F,v#7A5230", new int[]{5,7,9,7}, new int[]{6,10}, new int[]{14,5}, "k", null, ""},
            {"Vaquero", 0, new String[][]{{"................",".....oaaaao.....","....oaaaaaao....","....oaaaaaao....","oaaaaaaaaaaaaaao",".oooooooooooooo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbbo.","..obbbbbbbbbbo..","...oobbbbbboo...",".....oooooo.....","..ovvvvvvvvvvo..",".ovvvvvvvvvvvvo.",".ovvvvvvvvvvvvo."}}, "b#F2C9A0,a#8B5A2B,v#B03A2E", new int[]{5,7,9,7}, new int[]{6,10}, new int[]{14,5}, "k", null, ""},
            {"Espada", 8, new String[][]{{".......oo.......","......owgo......","......owgo......","......owgo......","......owgo......","......owgo......","......owgo......","......owgo......","......owgo......","...oooooooooo...","...oyyyyyyyyo...","...oooooooooo...","......okko......","......okko......",".....oyyyyo.....","......oooo......"}}, "b#9AA7B3,w#E8EEF2,g#9AA7B3,y#F5C542,k#6B4226,o#2B2B33", new int[]{5,4,9,4}, null, new int[]{13,1}, "o", null, "n"},
            {"Hacha", 8, new String[][]{{"................",".........oo.....","...ooooookko....","..ohwwwwwkko....",".ohwwwwwwkko....",".ohwwwwwwkko....",".ohwwwwwwkko....","..ohwwwwwkko....","...ooooookko....","........okko....","........okko....","........okko....","........okko....","........okko....","........okko....","........oooo...."}}, "b#9AA7B3,w#B9C4CE,h#EEF3F7,k#7A4A24,o#2B2B33", new int[]{3,4,6,4}, null, new int[]{13,1}, "o", null, "n"},
            {"Arco y flecha", 0, new String[][]{{"................",".....kw.........","....k.w.........","...k..w.........","...k..w.........","..k...w.........","..k...w......g..","..kryyyyyyyyyggg","..k...w......g..","..k...w.........","...k..w.........","...k..w.........","....k.w.........",".....kw.........","................","................"},{"................",".....k..........","....k.w.........","...k...w........","...k....w.......","..k......w......","..k......w...g..","..kr.....wyyyggg","..k......w...g..","..k......w......","...k....w.......","...k...w........","....k.w.........",".....k..........","................","................"}}, "b#8B5A2B,k#8B5A2B,w#EDEDED,y#D9B07A,g#9AA7B3,r#E84855", new int[]{3,4,6,4}, null, new int[]{13,1}, "o", null, "n"},
            {"Mineral de oro", 0, new String[][]{{".oooooooooooooo.",".obbbbbbbbbbbbo.",".obbbbbbxbdbbbo.",".obXxbbbbbbxXbo.",".obbbxbbbbbbxbo.",".obbbbbbbbbbbbo.",".odbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbdo.",".odbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obxbbbbbbbbxbo.",".obXxbdbbbbxXbo.",".obbbbbxbbbbbbo.",".oooooooooooooo.","................"}}, "b#8E8E8E,d#6E6E6E,o#3A3A3A,x#F5C542,X#FFF1A8", new int[]{5,6,9,6}, new int[]{6,9}, new int[]{13,0}, "k", null, ""},
            {"Mineral de cobre", 0, new String[][]{{".oooooooooooooo.",".obbbbbbbbbbbbo.",".obbbbbbxbdbbbo.",".obXxbbbbbbxXbo.",".obbbxbbbbbbxbo.",".obbbbbbbbbbbbo.",".odbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbdo.",".odbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obxbbbbbbbbxbo.",".obXxbdbbbbxXbo.",".obbbbbxbbbbbbo.",".oooooooooooooo.","................"}}, "b#8E8E8E,d#6E6E6E,o#3A3A3A,x#D9773B,X#5FC7A8", new int[]{5,6,9,6}, new int[]{6,9}, new int[]{13,0}, "k", null, ""},
            {"Mineral de hierro", 0, new String[][]{{".oooooooooooooo.",".obbbbbbbbbbbbo.",".obbbbbbxbdbbbo.",".obXxbbbbbbxXbo.",".obbbxbbbbbbxbo.",".obbbbbbbbbbbbo.",".odbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbdo.",".odbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obxbbbbbbbbxbo.",".obXxbdbbbbxXbo.",".obbbbbxbbbbbbo.",".oooooooooooooo.","................"}}, "b#8E8E8E,d#6E6E6E,o#3A3A3A,x#D8B7A0,X#F1E1D4", new int[]{5,6,9,6}, new int[]{6,9}, new int[]{13,0}, "k", null, ""},
            {"Mineral de bronce", 0, new String[][]{{".oooooooooooooo.",".obbbbbbbbbbbbo.",".obbbbbbxbdbbbo.",".obXxbbbbbbxXbo.",".obbbxbbbbbbxbo.",".obbbbbbbbbbbbo.",".odbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbdo.",".odbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obxbbbbbbbbxbo.",".obXxbdbbbbxXbo.",".obbbbbxbbbbbbo.",".oooooooooooooo.","................"}}, "b#8E8E8E,d#6E6E6E,o#3A3A3A,x#B07D3A,X#D9A75F", new int[]{5,6,9,6}, new int[]{6,9}, new int[]{13,0}, "k", null, ""},
            {"Mineral de diamante", 0, new String[][]{{".oooooooooooooo.",".obbbbbbbbbbbbo.",".obbbbbbxbdbbbo.",".obXxbbbbbbxXbo.",".obbbxbbbbbbxbo.",".obbbbbbbbbbbbo.",".odbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbdo.",".odbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obxbbbbbbbbxbo.",".obXxbdbbbbxXbo.",".obbbbbxbbbbbbo.",".oooooooooooooo.","................"}}, "b#8E8E8E,d#6E6E6E,o#3A3A3A,x#4FE3E1,X#C9FFFE", new int[]{5,6,9,6}, new int[]{6,9}, new int[]{13,0}, "k", null, ""},
            {"Mineral de titanio", 0, new String[][]{{".oooooooooooooo.",".obbbbbbbbbbbbo.",".obbbbbbxbdbbbo.",".obXxbbbbbbxXbo.",".obbbxbbbbbbxbo.",".obbbbbbbbbbbbo.",".odbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obbbbbbbbbbbdo.",".odbbbbbbbbbbbo.",".obbbbbbbbbbbbo.",".obxbbbbbbbbxbo.",".obXxbdbbbbxXbo.",".obbbbbxbbbbbbo.",".oooooooooooooo.","................"}}, "b#8E8E8E,d#6E6E6E,o#3A3A3A,x#B8C4D6,X#EEF3FA", new int[]{5,6,9,6}, new int[]{6,9}, new int[]{13,0}, "k", null, ""},
    };
}
